dist: trusty
sudo: required

os: linux

language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository ppa:nginx/stable -y 
  - sudo apt-get update -q
  - sudo apt-get install -qq -y libpcre3-dev
  - sudo apt-get install -qq -y zlib1g-dev

install:
  - sudo apt-get install -qq -y nginx
  - rm -rf njs
  - git clone https://github.com/ronanj/njs.git

script:
  - cd njs
  - ./configure
  - make -j2 > build.log 2>&1 || (cat build.log && exit 1)
  - echo "load_module "`pwd`"/objs/ngx_http_js_module.so;" > nginx.conf
  - echo "events {}" >> nginx.conf
  - sudo nginx -t -c `pwd`/nginx.conf